In [1]:
%pip install numpy -q
import numpy as np

Note: you may need to restart the kernel to use updated packages.


# Algoritmo de Eliminação de Gauss

In [87]:

X = np.matrix([[3,  2,  4],
               [1,  1,  2],
               [4,  3, -2]
               ])

y = np.matrix([[1], 
               [2],
               [3]
               ])


In [84]:
-22/3
#5/3

-7.333333333333333

In [162]:
n = X.shape[0]
a = np.float64(X.copy())
b = np.float64(y.copy())

for iVetor in range(0, a.shape[0]):
    print(a)
    print(' ')
    print(b)
    print('-' * 30)
    for iLinha in range(iVetor + 1, n):
        
        m = (a[iLinha, iVetor] / a[iVetor, iVetor])
        a[iLinha, iVetor] = 0
        
        for iProximasLinhas in range(iVetor + 1, n):
            a[iLinha, iProximasLinhas] = a[iLinha, iProximasLinhas] - (m * a[iVetor, iProximasLinhas])
        
        b[iLinha] = b[iLinha] - (m * b[iVetor])

#print(a)
#print(b)


[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
 
[[1.]
 [2.]
 [3.]]
------------------------------
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -7.33333333]]
 
[[1.        ]
 [1.66666667]
 [1.66666667]]
------------------------------
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]]
 
[[ 1.00000000e+00]
 [ 1.66666667e+00]
 [-4.44089210e-16]]
------------------------------


In [161]:
c = b.copy()

for iVetor in range(n - 1, -1, -1):
    s = 0
    
    for iLinha in range(iVetor + 1, n):
        s = s + (a[iVetor, iLinha] * (b[iLinha] / a[iLinha, iLinha]))
    
    c[iLinha] = (b[iLinha] - s) / a[iVetor, iVetor]
        
print(c)

[[ 1.        ]
 [ 1.66666667]
 [-3.33333333]]


In [166]:
n = X.shape[0]

a = np.float64(X.copy())
b = np.float64(y.copy())
c = b.copy()

for iVetor in range(0, a.shape[0]):
    for iLinha in range(iVetor + 1, n):
        
        m = (a[iLinha, iVetor] / a[iVetor, iVetor])
        a[iLinha, iVetor] = 0
        
        for iProximasLinhas in range(iVetor + 1, n):
            a[iLinha, iProximasLinhas] = a[iLinha, iProximasLinhas] - (m * a[iVetor, iProximasLinhas])
        
        b[iLinha] = b[iLinha] - (m * b[iVetor])

#for iVetor in range(n - 1, -1, -1):
#    s = 0   
#    for iLinha in range(iVetor + 1, n):
#        s = s + (a[iVetor, iLinha] * (b[iLinha] / a[iLinha, iLinha]))    
#    c[iVetor] = (b[iVetor] - s) / a[iVetor, iVetor]

for iVetor in range(n - 1, -1, -1):
    s = 0
    
    for iLinha in range(iVetor + 1, n):
        s = s + a[iVetor, iLinha] * c[iLinha]
    
    c[iVetor] = (b[iVetor] - s) / a[iVetor, iVetor]

print(c)

#print(a)
#print(b)


[[-3.00000000e+00]
 [ 5.00000000e+00]
 [ 5.55111512e-17]]


In [181]:
n = X.shape[0]
a = np.float64(X.copy())
b = np.float64(y.copy())
c = b.copy() 

for iVetor in range(0, a.shape[0]):
    for iLinha in range(iVetor + 1, n):
        m = (a[iLinha, iVetor] / a[iVetor, iVetor])
        a[iLinha, iVetor] = 0
        for iProximasLinhas in range(iVetor + 1, n):
            a[iLinha, iProximasLinhas] -= (m * a[iVetor, iProximasLinhas])
        b[iLinha] = b[iLinha] - (m * b[iVetor])

for iVetor in range(n - 1, -1, -1):
    s = 0
    for iLinha in range(iVetor + 1, n):
        s += a[iVetor, iLinha] * c[iLinha]
    c[iVetor] = (b[iVetor] - s) / a[iVetor, iVetor]

c

matrix([[-3.00000000e+00],
        [ 5.00000000e+00],
        [ 5.55111512e-17]])

In [204]:

class GaussElimination:

    def __init__(self):
        pass

    @staticmethod
    def _eliminate(X: np.matrix, y: np.matrix) -> tuple[np.matrix, np.matrix]:
        n = X.shape[0]
        a = np.float64(X.copy())
        b = np.float64(y.copy())
        for iVetor in range(0, a.shape[0]):
            for iLinha in range(iVetor + 1, n):
                m = (a[iLinha, iVetor] / a[iVetor, iVetor])
                a[iLinha, iVetor] = 0
                for iProximasLinhas in range(iVetor + 1, n):
                    a[iLinha, iProximasLinhas] -= (m * a[iVetor, iProximasLinhas])
                b[iLinha] = b[iLinha] - (m * b[iVetor])
        return (a, b)
    
    @staticmethod
    def _solve_system(a: np.matrix, b: np.matrix) -> np.matrix:
        c = b.copy()
        for iVetor in range(n - 1, -1, -1):
            s = 0
            for iLinha in range(iVetor + 1, n):
                s += a[iVetor, iLinha] * c[iLinha]
            c[iVetor] = (b[iVetor] - s) / a[iVetor, iVetor]
        return c
    
    @staticmethod
    def solve(X: np.matrix, y: np.matrix) -> np.matrix:
        this = GaussElimination()
        a, b = this._eliminate(X, y)
        c = this._solve_system(a, b)
        return c



In [213]:
%%timeit
GaussElimination.solve(X, y)


82.1 µs ± 1.69 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [214]:
%%timeit
np.linalg.solve(X, y)

4.71 µs ± 85.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
